name: Create Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Build Application
        run: |
          cmake -S . -B build -DPROJECT_VERSION=${{ github.event.inputs.version }}
          cmake --build build

      - name: Create and Push Git Tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: "Release ${{ github.event.inputs.version }}"
          files: build/src/hello_world
